# Base configuration - non-secret defaults
app:
  name: "meccaai"
  version: "0.1.0"
  debug: false

# MCP Configuration
mcp:
  config_path: "config/mcp/cursor.mcp.json"
  timeout: 30
  max_retries: 3
  endpoints_path: "config/mcp/endpoints.yaml"

# Tool Configuration
tools:
  auto_discover: true
  registry_paths:
    - "meccaai.tools"
  mcp_enabled: true

# AI Model Configuration
models:
  default_provider: "openai"
  openai:
    model: "gpt-4-turbo-preview"
    temperature: 0.1
    max_tokens: 4096
  anthropic:
    model: "claude-3-sonnet-20240229"
    temperature: 0.1
    max_tokens: 4096

# Memory/Vector Storage
memory:
  enabled: false
  provider: "chromadb"
  persist_directory: "./data/chroma"

# Telemetry
telemetry:
  enabled: false
  service_name: "meccaai"
  traces_endpoint: null
  metrics_endpoint: null