# Base configuration - non-secret defaults
app:
  name: "meccaai"
  version: "0.1.0"
  debug: false

# MCP Configuration
mcp:
  config_path: "config/mcp/cursor.mcp.json"
  timeout: 60
  max_retries: 3
  endpoints_path: "config/mcp/endpoints.yaml"

# Tool Configuration
tools:
  auto_discover: true
  registry_paths:
    - "meccaai.tools"
  mcp_enabled: true

# Agent Configuration  
agents:
  auto_handoff: true
  security_first_policy: true  # All requests must go through security agent first
  handoff_confidence_threshold: 0.2

# AI Model Configuration
models:
  default_provider: "openai"
  openai:
    model: "gpt-5-mini"
    temperature: 0.1
    max_tokens: 4096
  anthropic:
    model: "claude-3-sonnet-20240229"
    temperature: 0.1
    max_tokens: 4096

# Memory/Vector Storage
memory:
  enabled: false
  provider: "chromadb"
  persist_directory: "./data/chroma"

# Telemetry
telemetry:
  enabled: false
  service_name: "meccaai"
  traces_endpoint: null
  metrics_endpoint: null