# Base configuration - non-secret defaults
app:
  name: "meccaai"
  version: "0.1.0"
  debug: false

# MCP Configuration
mcp:
  config_path: "config/mcp/cursor.mcp.json"
  timeout: 600
  max_retries: 3
  endpoints_path: "config/mcp/endpoints.yaml"

# Tool Configuration
tools:
  auto_discover: true
  registry_paths:
    - "meccaai.tools"
  mcp_enabled: true

# Agent Configuration  
agents:
  auto_handoff: true
  security_first_policy: true  # All requests must go through security agent first
  handoff_confidence_threshold: 0.2

# AI Model Configuration (Bedrock only)
models:
  default_provider: "bedrock"
  bedrock:
    model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
    temperature: 0.1
    max_tokens: 8192
    timeout: 300.0

# AWS Bedrock Configuration
bedrock:
  aws_region: "ap-southeast-2"
  # AWS credentials loaded from environment variables
  aws_access_key_id: null
  aws_secret_access_key: null
  aws_session_token: null
  profile_name: null

# Tableau Configuration
tableau:
  server_url: "https://prod-apsoutheast-a.online.tableau.com"
  site_content_url: "meccalumos"
  token_name: "agent_api"
  api_version: "3.25"

# Memory/Vector Storage
memory:
  enabled: false
  provider: "chromadb"
  persist_directory: "./data/chroma"

# Logging Configuration
logging:
  # Local file logging - logs AI prompts, responses, thinking, and datetime info
  local:
    enabled: true
    log_file: "logs/ai_interactions.log"
    max_file_size_mb: 50
    backup_count: 10
    log_level: "DEBUG"
    
  # CloudWatch logging - sends logs to AWS CloudWatch
  cloudwatch:
    enabled: false
    log_group: "/meccaai/ai-interactions"
    log_stream_prefix: "ai-session"
    log_level: "INFO"
    max_message_size: 256000  # CloudWatch limit
    
# Telemetry
telemetry:
  enabled: false
  service_name: "meccaai"
  traces_endpoint: null
  metrics_endpoint: null