# AWS Bedrock Configuration
# Override base.yaml settings for Bedrock deployment

models:
  default_provider: "bedrock"
  bedrock:
    model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
    temperature: 0.1
    max_tokens: 4096
    timeout: 300.0

bedrock:
  aws_region: "us-east-1"
  # AWS credentials will be loaded from environment variables or AWS credentials file
  aws_access_key_id: null
  aws_secret_access_key: null
  aws_session_token: null
  profile_name: null

app:
  name: "meccaai-bedrock"
  version: "0.1.0"
  debug: false

tools:
  auto_discover: true
  registry_paths: ["meccaai.tools"]
  mcp_enabled: true

# Disable OpenAI specific settings when using Bedrock
# openai_api_key: null